name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  

jobs:
  assembleApks:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: create and checkout branch
        # push events already checked out the branch
        if: github.event_name == 'pull_request'
        env:
          BRANCH: ${{ github.head_ref }}
        run: git checkout -B "$BRANCH"

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"
          cache: 'gradle'

      - name: Build debug APK perm
        run: chmod +x ./gradlew 

      - name: Build debug APK
        run: ./gradlew assembleDebug 

      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debugApk
          path: app/build/outputs/apk
